#!/usr/bin/env bash
# Dispatcher: routes the commit-msg hook to the worktree-local
# .githooks/commit-msg-telemetry-backfill script.
#
# This dispatcher is the file the install script copies into the
# active hooks directory.  It is checked into the repo so the
# enforcement chain (install script → dispatcher → enforcement script)
# is fully version-controlled.  The active copy at the hooks-dir path
# is regenerated by scripts/git-hooks/install-commit-msg-dispatcher.sh.
#
# Updates to the rule itself happen in
# .githooks/commit-msg-telemetry-backfill (the enforcement script), not
# here.

set -euo pipefail

COMMIT_MSG_FILE="$1"
REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_SCRIPT="${REPO_ROOT}/.githooks/commit-msg-telemetry-backfill"

if [[ ! -x "$HOOK_SCRIPT" ]]; then
    echo "commit-msg dispatcher: ${HOOK_SCRIPT} is missing or not executable." >&2
    echo "Run scripts/git-hooks/install-commit-msg-dispatcher.sh to refresh." >&2
    exit 1
fi

exec "$HOOK_SCRIPT" "$COMMIT_MSG_FILE"
