"""Current schema-8 Step 1/2 Chat transition contracts."""

from __future__ import annotations

import asyncio
from uuid import UUID, uuid4

import pytest

from elspeth.contracts.composer_llm_audit import ComposerChatTurnStatus
from elspeth.web.composer.guided.chat_solver import Step1SourceChatResolution
from elspeth.web.composer.guided.resolved import SinkOutputResolved, SinkResolved
from elspeth.web.sessions._guided_step_chat import StepChatResult
from elspeth.web.sessions.routes.composer import guided as guided_route
from elspeth.web.sessions.routes.composer.guided_chat_atomic import GuidedChatProviderOutcome
from tests.integration.web.composer.guided.test_step_chat import TestStepChatCrossStep, _create_session, _outputs_path
from tests.unit.web._sync_asgi_client import SyncASGITestClient as TestClient


def _chat_body(turn: dict, message: str) -> dict[str, str]:
    return {
        "operation_id": str(uuid4()),
        "turn_token": turn["turn_token"],
        "message": message,
    }


def _source_resolution() -> Step1SourceChatResolution:
    return Step1SourceChatResolution(
        assistant_message="I prepared the CSV source form.",
        plugin="csv",
        filename="generated.csv",
        mime_type="text/csv",
        content="sku,quantity\nSKU-001,2\n",
        options={"schema": {"mode": "observed"}},
        observed_columns=("sku", "quantity"),
        sample_rows=({"sku": "SKU-001", "quantity": "2"},),
        on_validation_failure="discard",
    )


async def _resolved_source_provider(**_kwargs: object) -> GuidedChatProviderOutcome:
    resolution = _source_resolution()
    return GuidedChatProviderOutcome(
        chat=StepChatResult(
            assistant_message=resolution.assistant_message,
            status=ComposerChatTurnStatus.SUCCESS,
            latency_ms=1,
            error_class=None,
        ),
        source_resolution=resolution,
        sink_resolution=None,
        deferred_action=None,
    )


def test_uploaded_blob_does_not_create_a_chat_fast_path_and_inline_bytes_remain_not_applied(
    composer_test_client: TestClient,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """An upload may prefill the wizard, but Chat cannot bind or replace it.

    The first Chat projects only the source-plugin selection. A second Chat on
    the schema form reports generated bytes as ``not_applied`` and preserves
    the same authoritative turn and blob cohort.
    """
    client = composer_test_client
    session_id = _create_session(client)
    upload = client.post(
        f"/api/sessions/{session_id}/blobs/inline",
        json={
            "filename": "inventory.csv",
            "content": "sku,quantity\nSKU-001,2\n",
            "mime_type": "text/csv",
        },
    )
    assert upload.status_code == 201, upload.json()
    blobs_before = asyncio.run(client.app.state.blob_service.list_blobs(UUID(session_id)))
    initial_turn = client.get(f"/api/sessions/{session_id}/guided").json()["next_turn"]
    provider_calls = 0

    async def counted_provider(**kwargs: object) -> GuidedChatProviderOutcome:
        nonlocal provider_calls
        provider_calls += 1
        return await _resolved_source_provider(**kwargs)

    monkeypatch.setattr(guided_route, "_run_guided_chat_provider_attempt", counted_provider)
    selected = client.post(
        f"/api/sessions/{session_id}/guided/chat",
        json=_chat_body(initial_turn, 'Use the uploaded "inventory.csv" file.'),
    )

    assert selected.status_code == 200, selected.json()
    selected_json = selected.json()
    schema_turn = selected_json["next_turn"]
    assert schema_turn["type"] == "schema_form"
    assert selected_json["composition_state"]["sources"] == {}
    assert [item.id for item in asyncio.run(client.app.state.blob_service.list_blobs(UUID(session_id)))] == [
        item.id for item in blobs_before
    ]

    not_applied = client.post(
        f"/api/sessions/{session_id}/guided/chat",
        json=_chat_body(schema_turn, "Generate this CSV inline."),
    )

    assert not_applied.status_code == 200, not_applied.json()
    not_applied_json = not_applied.json()
    assert provider_calls == 2
    assert not_applied_json["assistant_message_kind"] == "synthetic_failure"
    assert not_applied_json["guided_session"]["chat_history"][-1]["synthetic_failure_reason"] == "not_applied"
    assert not_applied_json["next_turn"] == schema_turn
    assert not_applied_json["composition_state"]["sources"] == {}
    assert [item.id for item in asyncio.run(client.app.state.blob_service.list_blobs(UUID(session_id)))] == [
        item.id for item in blobs_before
    ]
    refreshed = client.get(f"/api/sessions/{session_id}/guided").json()
    assert refreshed["next_turn"] == schema_turn
    assert refreshed["composition_state"]["sources"] == {}


def test_step_2_chat_projects_sink_selection_without_committing_an_output(
    composer_test_client: TestClient,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A Step 2 sink suggestion advances only to the server-owned form."""
    client = composer_test_client
    session_id = _create_session(client)
    TestStepChatCrossStep._seed_csv_blob(client, session_id)
    TestStepChatCrossStep._configure_csv_source(client, session_id)
    current = client.get(f"/api/sessions/{session_id}/guided").json()
    assert current["guided_session"]["step"] == "step_2_sink"
    assert current["next_turn"]["type"] == "single_select"
    sink = SinkResolved(
        outputs=(
            SinkOutputResolved(
                name="main",
                plugin="json",
                options={
                    "path": _outputs_path(client, "chat-output.jsonl"),
                    "schema": {"mode": "observed"},
                    "mode": "write",
                    "collision_policy": "auto_increment",
                },
                required_fields=(),
                schema_mode="observed",
                on_write_failure="discard",
            ),
        )
    )

    async def sink_provider(**_kwargs: object) -> GuidedChatProviderOutcome:
        return GuidedChatProviderOutcome(
            chat=StepChatResult(
                assistant_message="I prepared the JSON output form.",
                status=ComposerChatTurnStatus.SUCCESS,
                latency_ms=1,
                error_class=None,
            ),
            source_resolution=None,
            sink_resolution=sink,
            deferred_action=None,
        )

    monkeypatch.setattr(guided_route, "_run_guided_chat_provider_attempt", sink_provider)
    response = client.post(
        f"/api/sessions/{session_id}/guided/chat",
        json=_chat_body(current["next_turn"], "Use JSON output."),
    )

    assert response.status_code == 200, response.json()
    response_json = response.json()
    assert response_json["next_turn"]["type"] == "schema_form"
    assert response_json["composition_state"]["outputs"] == []
    refreshed = client.get(f"/api/sessions/{session_id}/guided").json()
    assert refreshed["next_turn"] == response_json["next_turn"]
    assert refreshed["composition_state"]["outputs"] == []
