"""Built-in elspeth-lints rules."""

from __future__ import annotations

from elspeth_lints.rules.audit_evidence import (
    AUDIT_EVIDENCE_NOMINAL_RULE,
    GUARD_SYMMETRY_RULE,
    GVE_ATTRIBUTION_RULE,
    TIER_1_DECORATION_RULE,
)
from elspeth_lints.rules.composer import CATCH_ORDER_RULE, EXCEPTION_CHANNEL_RULE
from elspeth_lints.rules.immutability import FREEZE_GUARDS_RULE, FROZEN_ANNOTATIONS_RULE
from elspeth_lints.rules.manifest import CONTRACT_MANIFEST_RULE, SYMBOL_INVENTORY_RULE, TEST_TO_SOURCE_MAPPING_RULE
from elspeth_lints.rules.meta_no_new_bespoke_cicd_enforcer import RULE as META_NO_NEW_BESPOKE_CICD_ENFORCER_RULE
from elspeth_lints.rules.plugin_contract import COMPONENT_TYPE_RULE, OPTIONS_METADATA_RULE, PLUGIN_HASHES_RULE
from elspeth_lints.rules.trust_boundary import (
    TRUST_BOUNDARY_SCOPE_RULE,
    TRUST_BOUNDARY_TESTS_RULE,
    TRUST_BOUNDARY_TIER_RULE,
)
from elspeth_lints.rules.trust_tier import TIER_MODEL_RULE

BUILTIN_RULES = (
    META_NO_NEW_BESPOKE_CICD_ENFORCER_RULE,
    TIER_MODEL_RULE,
    OPTIONS_METADATA_RULE,
    COMPONENT_TYPE_RULE,
    PLUGIN_HASHES_RULE,
    CATCH_ORDER_RULE,
    EXCEPTION_CHANNEL_RULE,
    FREEZE_GUARDS_RULE,
    FROZEN_ANNOTATIONS_RULE,
    AUDIT_EVIDENCE_NOMINAL_RULE,
    TIER_1_DECORATION_RULE,
    GUARD_SYMMETRY_RULE,
    GVE_ATTRIBUTION_RULE,
    CONTRACT_MANIFEST_RULE,
    SYMBOL_INVENTORY_RULE,
    TEST_TO_SOURCE_MAPPING_RULE,
    TRUST_BOUNDARY_TESTS_RULE,
    TRUST_BOUNDARY_SCOPE_RULE,
    TRUST_BOUNDARY_TIER_RULE,
)

__all__ = [
    "AUDIT_EVIDENCE_NOMINAL_RULE",
    "BUILTIN_RULES",
    "CATCH_ORDER_RULE",
    "COMPONENT_TYPE_RULE",
    "CONTRACT_MANIFEST_RULE",
    "EXCEPTION_CHANNEL_RULE",
    "FREEZE_GUARDS_RULE",
    "FROZEN_ANNOTATIONS_RULE",
    "GUARD_SYMMETRY_RULE",
    "GVE_ATTRIBUTION_RULE",
    "META_NO_NEW_BESPOKE_CICD_ENFORCER_RULE",
    "OPTIONS_METADATA_RULE",
    "PLUGIN_HASHES_RULE",
    "SYMBOL_INVENTORY_RULE",
    "TEST_TO_SOURCE_MAPPING_RULE",
    "TIER_1_DECORATION_RULE",
    "TIER_MODEL_RULE",
    "TRUST_BOUNDARY_SCOPE_RULE",
    "TRUST_BOUNDARY_TESTS_RULE",
    "TRUST_BOUNDARY_TIER_RULE",
]
