"""Guided-mode protocol: turn types, payloads, responses, legal-turn matrix.

See docs/superpowers/specs/2026-05-11-composer-guided-mode-design.md §4.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Literal, TypedDict, cast
from uuid import UUID

from elspeth.web.catalog.knob_schema import SchemaFormPayload as SchemaFormPayload

# Wire sentinel for a blob-backed source's ``path`` knob in a schema_form payload.
# The emitter renders ``blob:<blob_ref>`` instead of the blob's ABSOLUTE
# storage_path (which would leak the deploy dir + OS username — see
# blobs/schemas.py, where storage_path is forbidden from HTTP responses); the
# step_1 commit handler re-resolves it to the real path via an authoritative
# by-id blob lookup. A filesystem path never starts with this prefix, so the
# sentinel is unambiguous.
BLOB_REF_PATH_PREFIX = "blob:"
GUIDED_MAX_COMPONENTS_PER_KIND = 256


class TurnType(StrEnum):
    """The closed taxonomy of turn types the protocol allows."""

    INSPECT_AND_CONFIRM = "inspect_and_confirm"
    SINGLE_SELECT = "single_select"
    MULTI_SELECT_WITH_CUSTOM = "multi_select_with_custom"
    SCHEMA_FORM = "schema_form"
    REVIEW_COMPONENTS = "review_components"
    PROPOSE_PIPELINE = "propose_pipeline"
    CONFIRM_WIRING = "confirm_wiring"


class _Option(TypedDict):
    id: str
    label: str
    hint: str | None


class _Observed(TypedDict):
    columns: Sequence[str]
    samples: Sequence[Mapping[str, Any]]
    warnings: Sequence[str]


class InspectAndConfirmPayload(TypedDict):
    observed: _Observed


class SingleSelectPayload(TypedDict):
    question: str
    options: Sequence[_Option]
    allow_custom: bool


class MultiSelectWithCustomPayload(TypedDict):
    question: str
    options: Sequence[_Option]
    default_chosen: Sequence[str]
    escape_label: str | None


ComponentReviewAction = Literal["add", "edit", "remove", "reorder", "finish"]


class _ComponentReviewItem(TypedDict):
    """Public reviewed-component summary; private plugin options stay server-side."""

    stable_id: str
    name: str
    plugin: str
    status: Literal["reviewed"]


class ComponentReviewPayload(TypedDict):
    """Stable-id-authoritative source/output collection review."""

    component_kind: Literal["source", "output"]
    items: Sequence[_ComponentReviewItem]
    allowed_actions: Sequence[ComponentReviewAction]


class ComponentTargetPayload(TypedDict):
    """Stable component identity; array positions are never edit authority."""

    kind: Literal["source", "node", "edge", "output"]
    stable_id: str


ProposalBlockerCode = Literal[
    "pipeline_invalid",
    "policy_review_required",
    "plugin_unavailable",
    "interpretation_required",
]


class _ProposalBlocker(TypedDict):
    """Allowlisted, server-authored blocker projection.

    ``code`` and ``category`` are closed structural vocabularies. ``summary``
    is generated by server templates; raw validator/provider/model text is not
    an admissible source for this field.
    """

    code: ProposalBlockerCode
    category: Literal["validation", "policy", "availability", "interpretation"]
    summary: str
    edit_target: ComponentTargetPayload | None


class _ProposalPluginRef(TypedDict):
    """Catalog identity only; Task 4 must verify membership/equivalence."""

    kind: Literal["source", "transform", "sink"]
    id: str


class _ProposalSourceSummary(TypedDict):
    stable_id: str
    label: str
    plugin: _ProposalPluginRef


class _ProposalEndpoint(TypedDict):
    kind: Literal["source", "node", "output"]
    stable_id: str


class _ProposalDiscardEndpoint(TypedDict):
    kind: Literal["discard"]


class _SourceSuccessFlow(TypedDict):
    kind: Literal["source_success"]
    branch: str | None


class _SourceValidationFailureFlow(TypedDict):
    kind: Literal["source_validation_failure"]


class _NodeSuccessFlow(TypedDict):
    kind: Literal["node_success"]
    branch: str | None


class _NodeErrorFlow(TypedDict):
    kind: Literal["node_error"]


class _GateRouteFlow(TypedDict):
    kind: Literal["gate_route"]
    route: str
    branch: str | None


class _GateForkFlow(TypedDict):
    kind: Literal["gate_fork"]
    routes: Sequence[str]
    branch: str


class _QueueContinueFlow(TypedDict):
    kind: Literal["queue_continue"]
    branch: str | None


class _CoalesceSuccessFlow(TypedDict):
    kind: Literal["coalesce_success"]
    branch: str | None


class _OutputWriteFailureFlow(TypedDict):
    kind: Literal["output_write_failure"]


_ProposalFlow = (
    _SourceSuccessFlow
    | _SourceValidationFailureFlow
    | _NodeSuccessFlow
    | _NodeErrorFlow
    | _GateRouteFlow
    | _GateForkFlow
    | _QueueContinueFlow
    | _CoalesceSuccessFlow
    | _OutputWriteFailureFlow
)


class _ProposalEdgeSummary(TypedDict):
    stable_id: str
    from_endpoint: _ProposalEndpoint
    to_endpoint: _ProposalEndpoint | _ProposalDiscardEndpoint
    flow: _ProposalFlow


class _ProposalGraphSummary(TypedDict):
    sources: Sequence[_ProposalSourceSummary]
    edges: Sequence[_ProposalEdgeSummary]


class _TransformBehavior(TypedDict):
    kind: Literal["transform"]


class _GateBehavior(TypedDict):
    kind: Literal["gate"]
    route_aliases: Sequence[str]
    fork_branches: Sequence[Mapping[str, Any]]


class _AggregationBehavior(TypedDict):
    kind: Literal["aggregation"]
    trigger_kinds: Sequence[Literal["count", "timeout", "condition"]]
    count: str | None
    timeout_seconds: float | None
    output_mode: Literal["default", "passthrough", "transform"]
    expected_output_count: str | None


class _QueueBehavior(TypedDict):
    kind: Literal["queue"]


class _CoalesceBehavior(TypedDict):
    kind: Literal["coalesce"]
    branch_aliases: Sequence[str]
    policy: Literal["require_all", "quorum", "best_effort", "first"]
    merge: Literal["union", "nested", "select"]


_ProposalNodeBehavior = _TransformBehavior | _GateBehavior | _AggregationBehavior | _QueueBehavior | _CoalesceBehavior


class _ProposalNodeSummary(TypedDict):
    stable_id: str
    label: str
    node_type: Literal["transform", "gate", "aggregation", "queue", "coalesce"]
    plugin: _ProposalPluginRef | None
    behavior: _ProposalNodeBehavior


class _ProposalOutputSummary(TypedDict):
    stable_id: str
    label: str
    plugin: _ProposalPluginRef


class _ProposalComponentCounts(TypedDict):
    sources: int
    nodes: int
    edges: int
    outputs: int


class ProposePipelinePayload(TypedDict):
    """Redacted display/audit projection of a durable pipeline proposal.

    This projection is deliberately non-executable: it contains only
    catalog-authoritative plugin identities, never component names, options,
    prompts, paths, inline content, secret references, or model-authored
    rationale. Exact canonical arguments remain in private proposal custody.
    Human copy is selected from exact server-owned template ids; structural
    labels are deterministic ordinals rather than canonical route, branch, or
    component names. Task 4 must validate catalog and private-proposal
    equivalence before publishing this projection. That projection must derive
    connectivity only from canonical runtime connection fields; it must never
    use ``CompositionState.edges``, which is a UI-only/stale projection.
    """

    proposal_id: str
    draft_hash: str
    # Revision discriminator: None for a first (transition auto-planned)
    # proposal; the superseded proposal's draft hash for a revision re-plan.
    # The tutorial frontend withholds "Review wiring" until the frozen-prompt
    # revision arrives (tutorial run 18: the pre-Send auto-proposal is a
    # source->sink passthrough and must not be acceptable there).
    supersedes_draft_hash: str | None
    summary: str
    rationale: str
    component_counts: _ProposalComponentCounts
    blockers: Sequence[_ProposalBlocker]
    graph: _ProposalGraphSummary
    nodes: Sequence[_ProposalNodeSummary]
    outputs: Sequence[_ProposalOutputSummary]
    edit_targets: Sequence[ComponentTargetPayload]


class _WireRowCardinality(TypedDict):
    input: Literal["none", "one", "batch", "branches", "many_producers"]
    output: Literal["one", "zero_or_one", "zero_or_many", "one_per_item", "one_per_branch_set", "expected_count"]
    expected_output_count: str | None


class _WireSchemaField(TypedDict):
    name: str
    type: str
    required: bool
    nullable: bool


class _WireStructuredOutputField(TypedDict):
    query: str
    field: str
    type: str
    enum_values: Sequence[str]


class _WireSourceReview(TypedDict):
    stable_id: str
    label: str
    plugin: str
    on_validation_failure: str
    guaranteed_fields: Sequence[str]
    row_cardinality: _WireRowCardinality


class _WireNodeReview(TypedDict):
    stable_id: str
    label: str
    node_type: str
    plugin: str | None
    behavior: Mapping[str, Any]
    required_fields: Sequence[str]
    guaranteed_fields: Sequence[str]
    row_cardinality: _WireRowCardinality
    structured_output_fields: Sequence[_WireStructuredOutputField]


class _WireBusinessSchema(TypedDict):
    mode: str
    fields: Sequence[_WireSchemaField]
    guaranteed_fields: Sequence[str]
    required_fields: Sequence[str]


class _WireOutputReview(TypedDict):
    stable_id: str
    label: str
    plugin: str
    on_write_failure: str
    required_fields: Sequence[str]
    business_schema: _WireBusinessSchema


class _WireConnectionReview(TypedDict):
    stable_id: str
    from_endpoint: _ProposalEndpoint
    to_endpoint: _ProposalEndpoint | _ProposalDiscardEndpoint
    flow: Mapping[str, Any]
    schema_contract: Mapping[str, Any] | None


class _WireProjection(TypedDict):
    sources: Sequence[_WireSourceReview]
    nodes: Sequence[_WireNodeReview]
    outputs: Sequence[_WireOutputReview]
    connections: Sequence[_WireConnectionReview]


class WireStageData(TypedDict):
    """Authoritative arbitrary-DAG review of one immutable candidate."""

    proposal_id: str
    draft_hash: str
    sources: Sequence[_WireSourceReview]
    nodes: Sequence[_WireNodeReview]
    outputs: Sequence[_WireOutputReview]
    connections: Sequence[_WireConnectionReview]
    semantic_contracts: Sequence[Mapping[str, Any]]
    warnings: Sequence[Mapping[str, Any]]
    blockers: Sequence[Mapping[str, Any]]
    can_confirm: bool


class ControlSignal(StrEnum):
    """Out-of-band signals carried in a TurnResponse instead of (or alongside) data."""

    EXIT_TO_FREEFORM = "exit_to_freeform"
    REJECT = "reject"
    BACK = "back"
    # Explicit "pass all fields through" escape hatch for MULTI_SELECT_WITH_CUSTOM
    # at STEP_2_SINK (the "Let source decide" button). An empty chosen +
    # custom_inputs pair is otherwise indistinguishable from a stale/buggy
    # client submitting nothing — PASSTHROUGH is the unambiguous, explicit
    # signal that fail-closed validation requires before accepting an empty
    # required-fields set in the current sink-stage transition.
    PASSTHROUGH = "passthrough"


class TurnResponse(TypedDict):
    """The user's typed response to a turn."""

    operation_id: str
    turn_token: str | None
    chosen: Sequence[str] | None
    edited_values: Mapping[str, Any] | None
    custom_inputs: Sequence[str] | None
    proposal_id: str | None
    draft_hash: str | None
    edit_target: ComponentTargetPayload | None
    control_signal: ControlSignal | None


class Turn(TypedDict):
    """A turn emitted to the user (server-emitted or LLM-emitted)."""

    type: str  # TurnType value
    step_index: int
    payload: Mapping[str, Any]


class GuidedStep(StrEnum):
    """Wizard step pointer."""

    STEP_1_SOURCE = "step_1_source"
    STEP_2_SINK = "step_2_sink"
    STEP_3_TRANSFORMS = "step_3_transforms"
    STEP_4_WIRE = "step_4_wire"


class ChatRole(StrEnum):
    """Closed taxonomy of chat-turn authors.

    A second author class for Phase A.5 — ``step_entry_opener`` (proactive
    server-initiated turn) — is intentionally absent here.  Phase A only
    distinguishes user-initiated and assistant-reply turns.  When openers
    land, the discriminator moves to ``ComposerChatTurn.initiator`` (audit
    record), not the ``ChatRole`` enum on the user-visible history — both
    a user prompt and a step-entry opener produce an ``assistant`` turn
    on the wire.  The plan §"Opener-specific invariant" relies on this
    separation.
    """

    USER = "user"
    ASSISTANT = "assistant"


@dataclass(frozen=True, slots=True)
class ChatTurn:
    """One conversational message in the per-step chat history (Phase A slice 5).

    Persisted in ``GuidedSession.chat_history``.  Trust tier: Tier 1
    (audit) — every field is server-authoritative.  ``seq`` is monotonic
    per session across all chat turns (user + assistant share the
    counter); on reload the frontend renders entries in ``seq`` order.

    ``ts_iso`` is the server-recorded ISO 8601 timestamp at which the
    turn entered the history.  It is informational for the UI; chrono
    ordering should still be driven by ``seq`` to avoid sort drift when
    the same wall clock-second carries two turns.

    ``step`` records the wizard step the user was on when the turn was
    produced.  Slice 5 keeps the same step for both user message and
    assistant reply (chat does not advance step state); the field is
    load-bearing for Phase A.5 openers and Phase B tool palettes where
    the step at *emission* may differ from the step at *display* if the
    user back-buttons.

    ``assistant_message_kind`` / ``synthetic_failure_reason`` are an exact
    persisted discriminator. User turns require both fields to be ``None``.
    Assistant turns require a kind; real replies require a ``None`` reason,
    while synthetic failures require one closed reason: quality rejection,
    provider unavailability, or a safe response that was deliberately not
    applied. There is no nested compatibility reader for omitted fields.
    """

    role: ChatRole
    content: str
    seq: int
    step: GuidedStep
    ts_iso: str
    assistant_message_kind: Literal["assistant", "synthetic_failure"] | None = None
    synthetic_failure_reason: Literal["quality_guard", "unavailable", "not_applied"] | None = None

    def __post_init__(self) -> None:
        if type(self.role) is not ChatRole:
            raise TypeError(f"role must be ChatRole, got {type(self.role).__name__}")
        if type(self.step) is not GuidedStep:
            raise TypeError(f"step must be GuidedStep, got {type(self.step).__name__}")
        if type(self.seq) is not int:
            raise TypeError(f"seq must be int, got {type(self.seq).__name__}")
        if self.assistant_message_kind is not None and self.assistant_message_kind not in ("assistant", "synthetic_failure"):
            raise ValueError(
                f"assistant_message_kind must be 'assistant', 'synthetic_failure', or None; got {self.assistant_message_kind!r}"
            )
        if self.synthetic_failure_reason is not None and self.synthetic_failure_reason not in (
            "quality_guard",
            "unavailable",
            "not_applied",
        ):
            raise ValueError(
                "synthetic_failure_reason must be 'quality_guard', 'unavailable', 'not_applied', or None; "
                f"got {self.synthetic_failure_reason!r}"
            )
        if self.synthetic_failure_reason is not None and self.assistant_message_kind != "synthetic_failure":
            raise ValueError("synthetic_failure_reason is set but assistant_message_kind is not 'synthetic_failure'")
        if self.role is ChatRole.USER and (self.assistant_message_kind is not None or self.synthetic_failure_reason is not None):
            raise ValueError("assistant_message_kind/synthetic_failure_reason are not applicable to a USER turn")
        if self.role is ChatRole.ASSISTANT and self.assistant_message_kind is None:
            raise ValueError("assistant_message_kind is required on an ASSISTANT turn")
        if self.assistant_message_kind == "synthetic_failure" and self.synthetic_failure_reason is None:
            raise ValueError("synthetic_failure_reason is required for a synthetic failure")
        if self.seq < 0:
            raise ValueError("seq must be >= 0")
        if type(self.content) is not str:
            raise TypeError(f"content must be str, got {type(self.content).__name__}")
        if self.content == "":
            raise ValueError("content must be non-empty")
        if type(self.ts_iso) is not str:
            raise TypeError(f"ts_iso must be str, got {type(self.ts_iso).__name__}")
        if self.ts_iso == "":
            raise ValueError("ts_iso must be non-empty")


_LEGAL_TURN_MATRIX: Mapping[GuidedStep, frozenset[TurnType]] = {
    GuidedStep.STEP_1_SOURCE: frozenset(
        {
            TurnType.INSPECT_AND_CONFIRM,
            TurnType.SINGLE_SELECT,
            TurnType.SCHEMA_FORM,
            TurnType.REVIEW_COMPONENTS,
        }
    ),
    GuidedStep.STEP_2_SINK: frozenset(
        {
            TurnType.SINGLE_SELECT,
            TurnType.MULTI_SELECT_WITH_CUSTOM,
            TurnType.SCHEMA_FORM,
            TurnType.REVIEW_COMPONENTS,
        }
    ),
    GuidedStep.STEP_3_TRANSFORMS: frozenset(
        {
            TurnType.PROPOSE_PIPELINE,
            TurnType.SINGLE_SELECT,
            TurnType.SCHEMA_FORM,
        }
    ),
    GuidedStep.STEP_4_WIRE: frozenset({TurnType.CONFIRM_WIRING}),
}


def legal_turn_types_for(step: GuidedStep) -> frozenset[TurnType]:
    """Return the frozen set of TurnType values legal at the given step."""
    return _LEGAL_TURN_MATRIX[step]


_STEP_INDEX: Mapping[GuidedStep, int] = {
    GuidedStep.STEP_1_SOURCE: 0,
    GuidedStep.STEP_2_SINK: 1,
    GuidedStep.STEP_3_TRANSFORMS: 2,
    GuidedStep.STEP_4_WIRE: 3,
}


def validate_current_turn(step: GuidedStep, turn: Mapping[str, Any]) -> TurnType:
    """Validate one exact current-schema turn and return its discriminator.

    Construction, durable load, and replay share this custody boundary. Those
    callers translate ``ValueError`` into the error class appropriate to the
    trust level of the turn they are handling.
    """

    if type(step) is not GuidedStep:
        raise ValueError("current-schema turn step must be GuidedStep")
    if not isinstance(turn, Mapping) or set(turn) != {"type", "step_index", "payload"}:
        raise ValueError("current-schema turn must have exactly type, step_index, and payload")
    raw_type = turn["type"]
    if type(raw_type) is not str:
        raise ValueError("current-schema turn type must be a string discriminator")
    try:
        turn_type = TurnType(raw_type)
    except ValueError as exc:
        raise ValueError("current-schema turn type is outside the closed vocabulary") from exc
    step_index = turn["step_index"]
    if type(step_index) is not int or step_index != _STEP_INDEX[step]:
        raise ValueError("current-schema turn step_index does not match its step")
    if turn_type not in legal_turn_types_for(step):
        raise ValueError("current-schema turn type is illegal for its step")
    payload = turn["payload"]
    if not isinstance(payload, Mapping):
        raise ValueError("current-schema turn payload must be a mapping")
    if error := validate_payload(turn_type, payload):
        raise ValueError(f"current-schema turn payload is invalid: {error}")
    return turn_type


_REQUIRED_KEYS: Mapping[TurnType, frozenset[str]] = {
    TurnType.INSPECT_AND_CONFIRM: frozenset({"observed"}),
    TurnType.SINGLE_SELECT: frozenset({"question", "options", "allow_custom"}),
    TurnType.MULTI_SELECT_WITH_CUSTOM: frozenset(
        {
            "question",
            "options",
            "default_chosen",
            "escape_label",
        }
    ),
    TurnType.SCHEMA_FORM: frozenset({"mode", "knobs", "prefilled"}),
    TurnType.REVIEW_COMPONENTS: frozenset({"component_kind", "items", "allowed_actions"}),
    TurnType.PROPOSE_PIPELINE: frozenset(
        {
            "proposal_id",
            "draft_hash",
            "supersedes_draft_hash",
            "summary",
            "rationale",
            "component_counts",
            "blockers",
            "graph",
            "nodes",
            "outputs",
            "edit_targets",
        }
    ),
    TurnType.CONFIRM_WIRING: frozenset(
        {
            "proposal_id",
            "draft_hash",
            "sources",
            "nodes",
            "outputs",
            "connections",
            "semantic_contracts",
            "warnings",
            "blockers",
            "can_confirm",
        }
    ),
}

_ALLOWED_KEYS: Mapping[TurnType, frozenset[str]] = {
    TurnType.INSPECT_AND_CONFIRM: frozenset({"observed"}),
    TurnType.SINGLE_SELECT: frozenset({"question", "options", "allow_custom"}),
    TurnType.MULTI_SELECT_WITH_CUSTOM: frozenset({"question", "options", "default_chosen", "escape_label"}),
    TurnType.SCHEMA_FORM: frozenset({"mode", "knobs", "prefilled", "plugin"}),
    TurnType.REVIEW_COMPONENTS: _REQUIRED_KEYS[TurnType.REVIEW_COMPONENTS],
    TurnType.PROPOSE_PIPELINE: _REQUIRED_KEYS[TurnType.PROPOSE_PIPELINE],
    TurnType.CONFIRM_WIRING: frozenset(
        {
            "proposal_id",
            "draft_hash",
            "sources",
            "nodes",
            "outputs",
            "connections",
            "semantic_contracts",
            "warnings",
            "blockers",
            "can_confirm",
        }
    ),
}

_PROPOSAL_BLOCKER_CATEGORY: Mapping[str, str] = {
    "pipeline_invalid": "validation",
    "policy_review_required": "policy",
    "plugin_unavailable": "availability",
    "interpretation_required": "interpretation",
}
PROPOSAL_SUMMARY_TEMPLATE = "guided.proposal.summary.full_graph.v1"
PROPOSAL_RATIONALE_TEMPLATE = "guided.proposal.rationale.review_required.v1"
_PROPOSAL_BLOCKER_SUMMARY: Mapping[str, str] = {
    "pipeline_invalid": "guided.proposal.blocker.pipeline_invalid.v1",
    "policy_review_required": "guided.proposal.blocker.policy_review_required.v1",
    "plugin_unavailable": "guided.proposal.blocker.plugin_unavailable.v1",
    "interpretation_required": "guided.proposal.blocker.interpretation_required.v1",
}
_COMPONENT_KINDS = frozenset({"source", "node", "edge", "output"})
_NODE_TYPES = frozenset({"transform", "gate", "aggregation", "queue", "coalesce"})
_FLOW_KINDS = frozenset(
    {
        "source_success",
        "source_validation_failure",
        "node_success",
        "node_error",
        "gate_route",
        "gate_fork",
        "queue_continue",
        "coalesce_success",
        "output_write_failure",
    }
)
_TRIGGER_KINDS = ("count", "timeout", "condition")
_COALESCE_POLICIES = frozenset({"require_all", "quorum", "best_effort", "first"})
_COALESCE_MERGES = frozenset({"union", "nested", "select"})
_MAX_PROPOSAL_COMPONENTS = 256
_MAX_PROPOSAL_EDGES = 1_024
_MAX_PROPOSAL_LABELS = 64


def proposal_blocker_summary(code: ProposalBlockerCode) -> str:
    """Return the sole public summary template id for a blocker code."""
    return _PROPOSAL_BLOCKER_SUMMARY[code]


def proposal_component_label(kind: Literal["source", "node", "output"], index: int) -> str:
    """Return the deterministic public label for a component position."""
    if kind not in ("source", "node", "output"):
        raise ValueError("proposal component label kind is outside the closed vocabulary")
    if type(index) is not int or index < 0 or index >= _MAX_PROPOSAL_COMPONENTS:
        raise ValueError("proposal component label index is outside the bounded range")
    return f"{kind}-{index + 1}"


def proposal_structural_label(kind: Literal["route", "branch"], index: int) -> str:
    """Return an opaque ordinal label without exposing canonical route names."""
    if kind not in ("route", "branch"):
        raise ValueError("proposal structural label kind is outside the closed vocabulary")
    if type(index) is not int or index < 0 or index >= _MAX_PROPOSAL_LABELS:
        raise ValueError("proposal structural label index is outside the bounded range")
    return f"{kind}-{index + 1}"


def _exact_nested_keys(value: object, expected: frozenset[str], path: str) -> str | None:
    if not isinstance(value, Mapping):
        return f"{path} must be a mapping (got {type(value).__name__})"
    missing = expected - value.keys()
    if missing:
        return f"{path} missing required keys: {sorted(missing)}"
    unexpected = value.keys() - expected
    if unexpected:
        return f"{path} has unexpected keys: {sorted(unexpected)}"
    return None


def _canonical_uuid_error(value: object, path: str) -> str | None:
    if type(value) is not str:
        return f"{path} must be a canonical UUID"
    try:
        parsed = UUID(value)
    except ValueError:
        return f"{path} must be a canonical UUID"
    if str(parsed) != value:
        return f"{path} must be a canonical UUID"
    return None


def _sequence_of_mappings(value: object, path: str) -> tuple[Sequence[Mapping[str, Any]] | None, str | None]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        return None, f"{path} must be a sequence"
    for index, item in enumerate(value):
        if not isinstance(item, Mapping):
            return None, f"{path}[{index}] must be a mapping"
    return cast(Sequence[Mapping[str, Any]], value), None


def _sequence_of_strings(value: object, path: str) -> tuple[tuple[str, ...] | None, str | None]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        return None, f"{path} must be a sequence"
    if any(type(item) is not str for item in value):
        return None, f"{path} must contain only strings"
    return tuple(cast(Sequence[str], value)), None


_MAX_CURRENT_TURN_ITEMS = 1_024
_MAX_CURRENT_TURN_TEXT = 65_536
_MAX_CURRENT_TURN_JSON_DEPTH = 16
_FIELD_KINDS = frozenset(
    {
        "text",
        "number-int",
        "number-float",
        "checkbox",
        "enum",
        "string-list",
        "blob-ref",
        "json-object",
        "json-array",
        "json-value",
    }
)
_FIELD_TIERS = frozenset({"essential", "common", "advanced"})
_ITEM_KINDS = frozenset({"text", "number-int", "number-float"})


def _current_text_error(value: object, path: str, *, nullable: bool = False, nonempty: bool = False) -> str | None:
    if value is None and nullable:
        return None
    if type(value) is not str:
        return f"{path} must be {'a string or null' if nullable else 'a string'}"
    if nonempty and not value:
        return f"{path} must be non-empty"
    if len(value) > _MAX_CURRENT_TURN_TEXT:
        return f"{path} exceeds the bounded text length"
    return None


def _current_sequence(
    value: object,
    path: str,
) -> tuple[Sequence[object] | None, str | None]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        return None, f"{path} must be a sequence"
    if len(value) > _MAX_CURRENT_TURN_ITEMS:
        return None, f"{path} exceeds the bounded item count"
    return cast(Sequence[object], value), None


def _current_string_sequence(
    value: object,
    path: str,
    *,
    unique: bool = False,
) -> tuple[tuple[str, ...] | None, str | None]:
    items, error = _current_sequence(value, path)
    if error is not None:
        return None, error
    assert items is not None
    decoded: list[str] = []
    for index, item in enumerate(items):
        if (error := _current_text_error(item, f"{path}[{index}]")) is not None:
            return None, error
        decoded.append(cast(str, item))
    if unique and len(decoded) != len(set(decoded)):
        return None, f"{path} must not contain duplicates"
    return tuple(decoded), None


def _public_json_error(value: object, path: str, *, depth: int = 0) -> str | None:
    """Validate a bounded JSON projection without coercion or object fallback."""

    if depth > _MAX_CURRENT_TURN_JSON_DEPTH:
        return f"{path} exceeds the bounded JSON depth"
    if value is None or type(value) in (bool, int):
        return None
    if type(value) is float:
        return None if math.isfinite(value) else f"{path} must contain only finite JSON numbers"
    if type(value) is str:
        return _current_text_error(value, path)
    if isinstance(value, Mapping):
        if len(value) > _MAX_CURRENT_TURN_ITEMS:
            return f"{path} exceeds the bounded item count"
        for key, item in value.items():
            if (error := _current_text_error(key, f"{path} key")) is not None:
                return error
            if (error := _public_json_error(item, f"{path}.{key}", depth=depth + 1)) is not None:
                return error
        return None
    items, error = _current_sequence(value, path)
    if error is not None:
        return f"{path} must contain only JSON values"
    assert items is not None
    for index, item in enumerate(items):
        if (error := _public_json_error(item, f"{path}[{index}]", depth=depth + 1)) is not None:
            return error
    return None


def _validate_options(value: object, path: str) -> tuple[tuple[str, ...] | None, str | None]:
    items, error = _current_sequence(value, path)
    if error is not None:
        return None, error
    assert items is not None
    option_ids: list[str] = []
    for index, item in enumerate(items):
        item_path = f"{path}[{index}]"
        if (error := _exact_nested_keys(item, frozenset({"id", "label", "hint"}), item_path)) is not None:
            return None, error
        assert isinstance(item, Mapping)
        if (error := _current_text_error(item["id"], f"{item_path}.id", nonempty=True)) is not None:
            return None, error
        if (error := _current_text_error(item["label"], f"{item_path}.label", nonempty=True)) is not None:
            return None, error
        if (error := _current_text_error(item["hint"], f"{item_path}.hint", nullable=True)) is not None:
            return None, error
        option_ids.append(cast(str, item["id"]))
    if len(option_ids) != len(set(option_ids)):
        return None, f"{path} must not contain duplicate option ids"
    return tuple(option_ids), None


def _validate_inspect_payload(payload: Mapping[str, Any]) -> str | None:
    observed = payload["observed"]
    if (error := _exact_nested_keys(observed, frozenset({"columns", "samples", "warnings"}), "payload.observed")) is not None:
        return error
    assert isinstance(observed, Mapping)
    if (error := _current_string_sequence(observed["columns"], "payload.observed.columns", unique=True)[1]) is not None:
        return error
    samples, error = _current_sequence(observed["samples"], "payload.observed.samples")
    if error is not None:
        return error
    assert samples is not None
    for index, sample in enumerate(samples):
        if not isinstance(sample, Mapping):
            return f"payload.observed.samples[{index}] must be a mapping"
        if (error := _public_json_error(sample, f"payload.observed.samples[{index}]")) is not None:
            return error
    return _current_string_sequence(observed["warnings"], "payload.observed.warnings")[1]


def _validate_single_select_payload(payload: Mapping[str, Any]) -> str | None:
    if (error := _current_text_error(payload["question"], "payload.question", nonempty=True)) is not None:
        return error
    if (error := _validate_options(payload["options"], "payload.options")[1]) is not None:
        return error
    if type(payload["allow_custom"]) is not bool:
        return "payload.allow_custom must be a bool"
    return None


def _validate_multi_select_payload(payload: Mapping[str, Any]) -> str | None:
    if (error := _current_text_error(payload["question"], "payload.question", nonempty=True)) is not None:
        return error
    option_ids, error = _validate_options(payload["options"], "payload.options")
    if error is not None:
        return error
    defaults, error = _current_string_sequence(payload["default_chosen"], "payload.default_chosen", unique=True)
    if error is not None:
        return error
    assert option_ids is not None and defaults is not None
    if not set(defaults).issubset(option_ids):
        return "payload.default_chosen must reference declared option ids"
    return _current_text_error(payload["escape_label"], "payload.escape_label", nullable=True)


def _validate_component_review_payload(payload: Mapping[str, Any]) -> str | None:
    component_kind = payload["component_kind"]
    if type(component_kind) is not str or component_kind not in {"source", "output"}:
        return "payload.component_kind is outside the closed component review vocabulary"
    items, error = _current_sequence(payload["items"], "payload.items")
    if error is not None:
        return error
    assert items is not None
    if not items:
        return "payload.items must contain at least one reviewed component"
    if len(items) > GUIDED_MAX_COMPONENTS_PER_KIND:
        return f"payload.items exceeds the {GUIDED_MAX_COMPONENTS_PER_KIND}-component limit"
    stable_ids: list[str] = []
    names: list[str] = []
    expected_item_keys = frozenset({"stable_id", "name", "plugin", "status"})
    for index, item in enumerate(items):
        path = f"payload.items[{index}]"
        if (error := _exact_nested_keys(item, expected_item_keys, path)) is not None:
            return error
        assert isinstance(item, Mapping)
        if (error := _canonical_uuid_error(item["stable_id"], f"{path}.stable_id")) is not None:
            return error
        for key in ("name", "plugin"):
            if (error := _current_text_error(item[key], f"{path}.{key}", nonempty=True)) is not None:
                return error
        if type(item["status"]) is not str or item["status"] != "reviewed":
            return f"{path}.status must be 'reviewed'"
        stable_ids.append(cast(str, item["stable_id"]))
        names.append(cast(str, item["name"]))
    if len(stable_ids) != len(set(stable_ids)):
        return "payload.items must not contain duplicate stable ids"
    if len(names) != len(set(names)):
        return "payload.items must not contain duplicate names"

    actions, error = _current_string_sequence(payload["allowed_actions"], "payload.allowed_actions", unique=True)
    if error is not None:
        return error
    assert actions is not None
    expected_actions = {"add", "edit", "reorder", "finish"}
    if len(items) > 1:
        expected_actions.add("remove")
    if set(actions) != expected_actions:
        return "payload.allowed_actions does not match the closed actions for this reviewed collection"
    return None


def _validate_knob_schema(value: object, path: str) -> str | None:
    if (error := _exact_nested_keys(value, frozenset({"fields"}), path)) is not None:
        return error
    assert isinstance(value, Mapping)
    fields, error = _current_sequence(value["fields"], f"{path}.fields")
    if error is not None:
        return error
    assert fields is not None
    seen_names: set[str] = set()
    visibility_gated: set[str] = set()
    required = frozenset({"name", "label", "kind", "required", "nullable"})
    optional = frozenset({"description", "tier", "default", "enum", "item_kind", "visible_when"})
    for index, item in enumerate(fields):
        field_path = f"{path}.fields[{index}]"
        if not isinstance(item, Mapping):
            return f"{field_path} must be a mapping"
        missing = required - item.keys()
        unexpected = item.keys() - required - optional
        if missing:
            return f"{field_path} missing required keys: {sorted(missing)}"
        if unexpected:
            return f"{field_path} has unexpected keys: {sorted(unexpected)}"
        for key in ("name", "label"):
            if (error := _current_text_error(item[key], f"{field_path}.{key}", nonempty=True)) is not None:
                return error
        name = cast(str, item["name"])
        if name in seen_names:
            return f"{path}.fields must not contain duplicate names"
        kind = item["kind"]
        if type(kind) is not str or kind not in _FIELD_KINDS:
            return f"{field_path}.kind is outside the closed field vocabulary"
        if type(item["required"]) is not bool or type(item["nullable"]) is not bool:
            return f"{field_path}.required and nullable must be bools"
        if "description" in item and (error := _current_text_error(item["description"], f"{field_path}.description")) is not None:
            return error
        if "tier" in item and (type(item["tier"]) is not str or item["tier"] not in _FIELD_TIERS):
            return f"{field_path}.tier is outside the closed tier vocabulary"
        if "default" in item and (error := _public_json_error(item["default"], f"{field_path}.default")) is not None:
            return error
        if "enum" in item:
            enum_values, error = _current_string_sequence(item["enum"], f"{field_path}.enum", unique=True)
            if error is not None:
                return error
            if kind != "enum" or not enum_values:
                return f"{field_path}.enum must be a non-empty list for an enum field"
        elif kind == "enum":
            return f"{field_path}.enum is required for an enum field"
        if "item_kind" in item:
            if type(item["item_kind"]) is not str or item["item_kind"] not in _ITEM_KINDS:
                return f"{field_path}.item_kind is outside the closed item vocabulary"
            if kind != "string-list":
                return f"{field_path}.item_kind is only valid for string-list fields"
        elif kind == "string-list":
            return f"{field_path}.item_kind is required for string-list fields"
        if "visible_when" in item:
            predicate = item["visible_when"]
            if (error := _exact_nested_keys(predicate, frozenset({"field", "equals"}), f"{field_path}.visible_when")) is not None:
                return error
            assert isinstance(predicate, Mapping)
            target = predicate["field"]
            if type(target) is not str or target not in seen_names or target in visibility_gated:
                return f"{field_path}.visible_when.field must reference one ungated earlier field"
            if (error := _public_json_error(predicate["equals"], f"{field_path}.visible_when.equals")) is not None:
                return error
            visibility_gated.add(name)
        seen_names.add(name)
    return None


def _validate_schema_form_payload(payload: Mapping[str, Any]) -> str | None:
    if payload["mode"] != "plugin_options":
        return "payload.mode must be 'plugin_options'"
    if "plugin" not in payload:
        return "payload for schema_form mode=plugin_options missing required keys: ['plugin']"
    if (error := _catalog_plugin_id_error(payload["plugin"], "payload.plugin")) is not None:
        return error
    if (error := _validate_knob_schema(payload["knobs"], "payload.knobs")) is not None:
        return error
    if not isinstance(payload["prefilled"], Mapping):
        return "payload.prefilled must be a mapping"
    return _public_json_error(payload["prefilled"], "payload.prefilled")


def _validate_string_mapping(value: object, path: str) -> str | None:
    if not isinstance(value, Mapping):
        return f"{path} must be a mapping"
    if len(value) > _MAX_CURRENT_TURN_ITEMS:
        return f"{path} exceeds the bounded item count"
    for key, item in value.items():
        if (error := _current_text_error(key, f"{path} key", nonempty=True)) is not None:
            return error
        if (error := _current_text_error(item, f"{path}.{key}", nonempty=True)) is not None:
            return error
    return None


def _validate_wire_payload(payload: Mapping[str, Any]) -> str | None:
    if (error := _canonical_uuid_error(payload["proposal_id"], "payload.proposal_id")) is not None:
        return error
    draft_hash = payload["draft_hash"]
    if type(draft_hash) is not str or len(draft_hash) != 64 or any(char not in "0123456789abcdef" for char in draft_hash):
        return "payload.draft_hash must be 64 lowercase hexadecimal characters"
    cardinality_keys = frozenset({"input", "output", "expected_output_count"})
    cardinality_inputs = frozenset({"none", "one", "batch", "branches", "many_producers"})
    cardinality_outputs = frozenset({"one", "zero_or_one", "zero_or_many", "one_per_item", "one_per_branch_set", "expected_count"})

    def validate_cardinality(value: object, path: str) -> str | None:
        if (nested_error := _exact_nested_keys(value, cardinality_keys, path)) is not None:
            return nested_error
        assert isinstance(value, Mapping)
        if value["input"] not in cardinality_inputs or value["output"] not in cardinality_outputs:
            return f"{path} is outside the closed cardinality vocabulary"
        count = value["expected_output_count"]
        if count is not None and (nested_error := _canonical_integer_string_error(count, f"{path}.expected_output_count", positive=False)):
            return nested_error
        if (count is not None) != (value["output"] == "expected_count"):
            return f"{path}.expected_output_count must exactly bind expected_count"
        return None

    sources, error = _current_sequence(payload["sources"], "payload.sources")
    if error is not None:
        return error
    nodes, error = _current_sequence(payload["nodes"], "payload.nodes")
    if error is not None:
        return error
    outputs, error = _current_sequence(payload["outputs"], "payload.outputs")
    if error is not None:
        return error
    assert sources is not None and nodes is not None and outputs is not None
    component_ids: dict[str, str] = {}
    source_keys = frozenset({"stable_id", "label", "plugin", "on_validation_failure", "guaranteed_fields", "row_cardinality"})
    for index, source in enumerate(sources):
        path = f"payload.sources[{index}]"
        if (error := _exact_nested_keys(source, source_keys, path)) is not None:
            return error
        assert isinstance(source, Mapping)
        if (error := _canonical_uuid_error(source["stable_id"], f"{path}.stable_id")) is not None:
            return error
        if source["stable_id"] in component_ids:
            return f"{path}.stable_id duplicates another component"
        component_ids[source["stable_id"]] = "source"
        if (error := _current_text_error(source["label"], f"{path}.label", nonempty=True)) is not None:
            return error
        if (error := _catalog_plugin_id_error(source["plugin"], f"{path}.plugin")) is not None:
            return error
        if error := _current_text_error(source["on_validation_failure"], f"{path}.on_validation_failure", nonempty=True):
            return error
        if (error := _current_string_sequence(source["guaranteed_fields"], f"{path}.guaranteed_fields")[1]) is not None:
            return error
        if (error := validate_cardinality(source["row_cardinality"], f"{path}.row_cardinality")) is not None:
            return error

    node_keys = frozenset(
        {
            "stable_id",
            "label",
            "node_type",
            "plugin",
            "behavior",
            "required_fields",
            "guaranteed_fields",
            "row_cardinality",
            "structured_output_fields",
        }
    )
    for index, node in enumerate(nodes):
        path = f"payload.nodes[{index}]"
        if (error := _exact_nested_keys(node, node_keys, path)) is not None:
            return error
        assert isinstance(node, Mapping)
        if (error := _canonical_uuid_error(node["stable_id"], f"{path}.stable_id")) is not None:
            return error
        if node["stable_id"] in component_ids:
            return f"{path}.stable_id duplicates another component"
        component_ids[node["stable_id"]] = "node"
        if (error := _current_text_error(node["label"], f"{path}.label", nonempty=True)) is not None:
            return error
        if node["plugin"] is not None and (error := _catalog_plugin_id_error(node["plugin"], f"{path}.plugin")) is not None:
            return error
        if (error := _validate_node_behavior(node["node_type"], node["behavior"], path)) is not None:
            return error
        for name in ("required_fields", "guaranteed_fields"):
            if (error := _current_string_sequence(node[name], f"{path}.{name}")[1]) is not None:
                return error
        if (error := validate_cardinality(node["row_cardinality"], f"{path}.row_cardinality")) is not None:
            return error
        if (error := _public_json_error(node["structured_output_fields"], f"{path}.structured_output_fields")) is not None:
            return error

    output_keys = frozenset({"stable_id", "label", "plugin", "on_write_failure", "required_fields", "business_schema"})
    schema_keys = frozenset({"mode", "fields", "guaranteed_fields", "required_fields"})
    for index, output in enumerate(outputs):
        path = f"payload.outputs[{index}]"
        if (error := _exact_nested_keys(output, output_keys, path)) is not None:
            return error
        assert isinstance(output, Mapping)
        if (error := _canonical_uuid_error(output["stable_id"], f"{path}.stable_id")) is not None:
            return error
        if output["stable_id"] in component_ids:
            return f"{path}.stable_id duplicates another component"
        component_ids[output["stable_id"]] = "output"
        for name in ("label", "on_write_failure"):
            if (error := _current_text_error(output[name], f"{path}.{name}", nonempty=True)) is not None:
                return error
        if (error := _catalog_plugin_id_error(output["plugin"], f"{path}.plugin")) is not None:
            return error
        if (error := _current_string_sequence(output["required_fields"], f"{path}.required_fields")[1]) is not None:
            return error
        schema = output["business_schema"]
        if (error := _exact_nested_keys(schema, schema_keys, f"{path}.business_schema")) is not None:
            return error
        if (error := _public_json_error(schema, f"{path}.business_schema")) is not None:
            return error

    connections, error = _current_sequence(payload["connections"], "payload.connections")
    if error is not None:
        return error
    assert connections is not None
    contract_keys = frozenset({"from", "to", "producer_guarantees", "consumer_requires", "missing_fields", "satisfied"})
    connection_keys = frozenset({"stable_id", "from_endpoint", "to_endpoint", "flow", "schema_contract"})
    seen_connections: set[str] = set()
    for index, connection in enumerate(connections):
        path = f"payload.connections[{index}]"
        if (error := _exact_nested_keys(connection, connection_keys, path)) is not None:
            return error
        assert isinstance(connection, Mapping)
        if (error := _canonical_uuid_error(connection["stable_id"], f"{path}.stable_id")) is not None:
            return error
        if connection["stable_id"] in seen_connections:
            return f"{path}.stable_id duplicates another connection"
        seen_connections.add(connection["stable_id"])
        if error := _validate_proposal_endpoint(connection["from_endpoint"], f"{path}.from_endpoint", allow_discard=False):
            return error
        if error := _validate_proposal_endpoint(connection["to_endpoint"], f"{path}.to_endpoint", allow_discard=True):
            return error
        assert isinstance(connection["from_endpoint"], Mapping) and isinstance(connection["to_endpoint"], Mapping)
        for endpoint_name in ("from_endpoint", "to_endpoint"):
            endpoint = connection[endpoint_name]
            if endpoint.get("kind") != "discard" and component_ids.get(endpoint.get("stable_id")) != endpoint.get("kind"):
                return f"{path}.{endpoint_name} does not resolve to its advertised component kind"
        if (error := _validate_proposal_flow(connection["flow"], f"{path}.flow")) is not None:
            return error
        contract = connection["schema_contract"]
        if contract is None:
            continue
        contract_path = f"{path}.schema_contract"
        if (error := _exact_nested_keys(contract, contract_keys, contract_path)) is not None:
            return error
        assert isinstance(contract, Mapping)
        for key in ("from", "to"):
            if (error := _current_text_error(contract[key], f"{contract_path}.{key}", nonempty=True)) is not None:
                return error
        for key in ("producer_guarantees", "consumer_requires", "missing_fields"):
            if (error := _current_string_sequence(contract[key], f"{contract_path}.{key}")[1]) is not None:
                return error
        if type(contract["satisfied"]) is not bool:
            return f"{contract_path}.satisfied must be a bool"

    for field_name in ("semantic_contracts", "warnings", "blockers"):
        items, error = _current_sequence(payload[field_name], f"payload.{field_name}")
        if error is not None:
            return error
        assert items is not None
        for index, item in enumerate(items):
            if not isinstance(item, Mapping):
                return f"payload.{field_name}[{index}] must be a mapping"
            if (error := _public_json_error(item, f"payload.{field_name}[{index}]")) is not None:
                return error
    if type(payload["can_confirm"]) is not bool:
        return "payload.can_confirm must be a bool"
    if payload["can_confirm"] != (not payload["blockers"]):
        return "payload.can_confirm must exactly reflect the absence of blockers"
    return None


def _catalog_plugin_id_error(value: object, path: str) -> str | None:
    if type(value) is not str or not value or len(value) > 64:
        return f"{path} must be a bounded catalog plugin identifier"
    if not value[0].islower() or not value[0].isalpha() or any(not (char.islower() or char.isdigit() or char == "_") for char in value):
        return f"{path} must use the catalog plugin identifier grammar"
    return None


def _validate_plugin_ref(value: object, path: str, expected_kind: Literal["source", "transform", "sink"]) -> str | None:
    if (error := _exact_nested_keys(value, frozenset({"kind", "id"}), path)) is not None:
        return error
    assert isinstance(value, Mapping)
    if value["kind"] != expected_kind:
        return f"{path}.kind must be {expected_kind!r}"
    return _catalog_plugin_id_error(value["id"], f"{path}.id")


def _structural_alias_error(value: object, kind: Literal["route", "branch"], path: str) -> str | None:
    if type(value) is not str or not value.startswith(f"{kind}-"):
        return f"{path} must be an exact server ordinal alias"
    suffix = value.removeprefix(f"{kind}-")
    if not suffix.isdigit() or str(int(suffix)) != suffix or not 1 <= int(suffix) <= _MAX_PROPOSAL_LABELS:
        return f"{path} must be an exact server ordinal alias"
    return None


def _validate_alias_sequence(
    value: object,
    *,
    kind: Literal["route", "branch"],
    path: str,
    minimum: int = 0,
) -> tuple[tuple[str, ...] | None, str | None]:
    labels, error = _sequence_of_strings(value, path)
    if error is not None:
        return None, error
    assert labels is not None
    if len(labels) < minimum or len(labels) > _MAX_PROPOSAL_LABELS:
        return None, f"{path} must contain between {minimum} and {_MAX_PROPOSAL_LABELS} labels"
    if len(labels) != len(set(labels)):
        return None, f"{path} must not contain duplicate aliases"
    for index, label in enumerate(labels):
        if (error := _structural_alias_error(label, kind, f"{path}[{index}]")) is not None:
            return None, error
    return labels, None


def _finite_positive_number_error(value: object, path: str) -> str | None:
    if isinstance(value, bool) or not isinstance(value, int | float):
        return f"{path} must be a finite positive number or null"
    try:
        numeric = float(value)
    except OverflowError:
        return f"{path} must be a finite positive number"
    if not math.isfinite(numeric) or numeric <= 0:
        return f"{path} must be a finite positive number"
    return None


def _canonical_integer_string_error(value: object, path: str, *, positive: bool) -> str | None:
    if type(value) is not str or not value:
        return f"{path} must be a canonical decimal integer string or null"
    digits = value if not value.startswith("-") else value[1:]
    if not digits.isdigit() or (len(digits) > 1 and digits.startswith("0")) or value == "-0":
        return f"{path} must be a canonical decimal integer string or null"
    if positive and (value.startswith("-") or value == "0"):
        return f"{path} must be a canonical positive decimal integer string or null"
    return None


def _validate_node_behavior(node_type: object, behavior: object, path: str) -> str | None:
    if node_type not in _NODE_TYPES:
        return f"{path}.node_type is not in the closed node vocabulary"
    if not isinstance(behavior, Mapping):
        return f"{path}.behavior must be a mapping"
    if "kind" not in behavior:
        return f"{path}.behavior missing required keys: ['kind']"
    if behavior.get("kind") != node_type:
        return f"{path}.behavior.kind must match node_type"
    behavior_path = f"{path}.behavior"
    if node_type in ("transform", "queue"):
        return _exact_nested_keys(behavior, frozenset({"kind"}), behavior_path)
    if node_type == "gate":
        expected = frozenset({"kind", "route_aliases", "fork_branches"})
        if (error := _exact_nested_keys(behavior, expected, behavior_path)) is not None:
            return error
        route_aliases, error = _validate_alias_sequence(
            behavior["route_aliases"], kind="route", path=f"{behavior_path}.route_aliases", minimum=1
        )
        if error is not None:
            return error
        fork_branches, error = _sequence_of_mappings(behavior["fork_branches"], f"{behavior_path}.fork_branches")
        if error is not None:
            return error
        assert route_aliases is not None and fork_branches is not None
        if len(fork_branches) > _MAX_PROPOSAL_LABELS:
            return f"{behavior_path}.fork_branches exceeds the bounded size"
        seen_branches: set[str] = set()
        fork_route_sequence: tuple[str, ...] | None = None
        for index, fork_branch in enumerate(fork_branches):
            item_path = f"{behavior_path}.fork_branches[{index}]"
            if (error := _exact_nested_keys(fork_branch, frozenset({"routes", "branch"}), item_path)) is not None:
                return error
            routes, error = _validate_alias_sequence(fork_branch["routes"], kind="route", path=f"{item_path}.routes", minimum=1)
            if error is not None:
                return error
            if (error := _structural_alias_error(fork_branch["branch"], "branch", f"{item_path}.branch")) is not None:
                return error
            if fork_branch["branch"] in seen_branches:
                return f"{behavior_path}.fork_branches must define each physical branch once"
            seen_branches.add(fork_branch["branch"])
            assert routes is not None
            if any(route not in route_aliases for route in routes):
                return f"{item_path}.routes must resolve to this gate's route_aliases"
            if fork_route_sequence is None:
                fork_route_sequence = routes
            elif routes != fork_route_sequence:
                return f"{behavior_path}.fork_branches must share one exact ordered route sequence"
        return None
    if node_type == "aggregation":
        expected = frozenset({"kind", "trigger_kinds", "count", "timeout_seconds", "output_mode", "expected_output_count"})
        if (error := _exact_nested_keys(behavior, expected, behavior_path)) is not None:
            return error
        trigger_kinds, error = _sequence_of_strings(behavior["trigger_kinds"], f"{behavior_path}.trigger_kinds")
        if error is not None:
            return error
        assert trigger_kinds is not None
        if (
            len(trigger_kinds) != len(set(trigger_kinds))
            or tuple(kind for kind in _TRIGGER_KINDS if kind in trigger_kinds) != trigger_kinds
        ):
            return f"{behavior_path}.trigger_kinds must be a unique canonical subsequence of the closed trigger vocabulary"
        count = behavior["count"]
        if count is not None and (error := _canonical_integer_string_error(count, f"{behavior_path}.count", positive=True)) is not None:
            return error
        if (count is not None) != ("count" in trigger_kinds):
            return f"{behavior_path}.count must exactly match the count trigger kind"
        timeout_seconds = behavior["timeout_seconds"]
        if (
            timeout_seconds is not None
            and (error := _finite_positive_number_error(timeout_seconds, f"{behavior_path}.timeout_seconds")) is not None
        ):
            return error
        if (timeout_seconds is not None) != ("timeout" in trigger_kinds):
            return f"{behavior_path}.timeout_seconds must exactly match the timeout trigger kind"
        if behavior["output_mode"] not in ("default", "passthrough", "transform"):
            return f"{behavior_path}.output_mode is outside the closed vocabulary"
        expected_count = behavior["expected_output_count"]
        if (
            expected_count is not None
            and (error := _canonical_integer_string_error(expected_count, f"{behavior_path}.expected_output_count", positive=False))
            is not None
        ):
            return error
        return None
    expected = frozenset({"kind", "branch_aliases", "policy", "merge"})
    if (error := _exact_nested_keys(behavior, expected, behavior_path)) is not None:
        return error
    _, error = _validate_alias_sequence(behavior["branch_aliases"], kind="branch", path=f"{behavior_path}.branch_aliases", minimum=2)
    if error is not None:
        return error
    if behavior["policy"] not in _COALESCE_POLICIES:
        return f"{behavior_path}.policy is outside the closed vocabulary"
    if behavior["merge"] not in _COALESCE_MERGES:
        return f"{behavior_path}.merge is outside the closed vocabulary"
    return None


def _validate_component_target(value: object, path: str) -> str | None:
    error = _exact_nested_keys(value, frozenset({"kind", "stable_id"}), path)
    if error is not None:
        return error
    target = value
    assert isinstance(target, Mapping)
    if target["kind"] not in _COMPONENT_KINDS:
        return f"{path}.kind is not in the closed component vocabulary"
    return _canonical_uuid_error(target["stable_id"], f"{path}.stable_id")


def _validate_proposal_endpoint(value: object, path: str, *, allow_discard: bool) -> str | None:
    if not isinstance(value, Mapping):
        return f"{path} must be a mapping"
    if value.get("kind") == "discard":
        if not allow_discard:
            return f"{path} cannot be discard"
        return _exact_nested_keys(value, frozenset({"kind"}), path)
    if (error := _exact_nested_keys(value, frozenset({"kind", "stable_id"}), path)) is not None:
        return error
    if value["kind"] not in ("source", "node", "output"):
        return f"{path}.kind is outside the closed endpoint vocabulary"
    return _canonical_uuid_error(value["stable_id"], f"{path}.stable_id")


def _validate_proposal_flow(value: object, path: str) -> str | None:
    if not isinstance(value, Mapping):
        return f"{path} must be a mapping"
    kind = value.get("kind")
    if kind not in _FLOW_KINDS:
        return f"{path}.kind is outside the closed flow vocabulary"
    if kind in ("source_success", "node_success", "queue_continue", "coalesce_success"):
        if (error := _exact_nested_keys(value, frozenset({"kind", "branch"}), path)) is not None:
            return error
        branch = value["branch"]
        if branch is not None:
            return _structural_alias_error(branch, "branch", f"{path}.branch")
        return None
    if kind in ("source_validation_failure", "node_error", "output_write_failure"):
        return _exact_nested_keys(value, frozenset({"kind"}), path)
    if kind == "gate_route":
        if (error := _exact_nested_keys(value, frozenset({"kind", "route", "branch"}), path)) is not None:
            return error
        if (error := _structural_alias_error(value["route"], "route", f"{path}.route")) is not None:
            return error
        branch = value["branch"]
        if branch is not None:
            return _structural_alias_error(branch, "branch", f"{path}.branch")
        return None
    if (error := _exact_nested_keys(value, frozenset({"kind", "routes", "branch"}), path)) is not None:
        return error
    _, error = _validate_alias_sequence(value["routes"], kind="route", path=f"{path}.routes", minimum=1)
    if error is not None:
        return error
    return _structural_alias_error(value["branch"], "branch", f"{path}.branch")


def _validate_propose_pipeline_payload(payload: Mapping[str, Any]) -> str | None:
    if (error := _canonical_uuid_error(payload["proposal_id"], "payload.proposal_id")) is not None:
        return error
    draft_hash = payload["draft_hash"]
    if type(draft_hash) is not str or len(draft_hash) != 64 or any(char not in "0123456789abcdef" for char in draft_hash):
        return "payload.draft_hash must be 64 lowercase hexadecimal characters"
    supersedes = payload["supersedes_draft_hash"]
    if supersedes is not None and (
        type(supersedes) is not str or len(supersedes) != 64 or any(char not in "0123456789abcdef" for char in supersedes)
    ):
        return "payload.supersedes_draft_hash must be null or 64 lowercase hexadecimal characters"
    if payload["summary"] != PROPOSAL_SUMMARY_TEMPLATE:
        return "payload.summary must be the exact server-owned template id"
    if payload["rationale"] != PROPOSAL_RATIONALE_TEMPLATE:
        return "payload.rationale must be the exact server-owned template id"

    counts = payload["component_counts"]
    if error := _exact_nested_keys(counts, frozenset({"sources", "nodes", "edges", "outputs"}), "payload.component_counts"):
        return error
    assert isinstance(counts, Mapping)
    for kind, maximum in (
        ("sources", _MAX_PROPOSAL_COMPONENTS),
        ("nodes", _MAX_PROPOSAL_COMPONENTS),
        ("edges", _MAX_PROPOSAL_EDGES),
        ("outputs", _MAX_PROPOSAL_COMPONENTS),
    ):
        count = counts[kind]
        if type(count) is not int or count < 0 or count > maximum:
            return f"payload.component_counts.{kind} is outside the bounded range"
    if counts["sources"] == 0 or counts["outputs"] == 0:
        return "payload.component_counts requires at least one source and one output"

    graph = payload["graph"]
    if (error := _exact_nested_keys(graph, frozenset({"sources", "edges"}), "payload.graph")) is not None:
        return error
    assert isinstance(graph, Mapping)
    sources, error = _sequence_of_mappings(graph["sources"], "payload.graph.sources")
    if error is not None:
        return error
    assert sources is not None
    for index, source in enumerate(sources):
        path = f"payload.graph.sources[{index}]"
        if (error := _exact_nested_keys(source, frozenset({"stable_id", "label", "plugin"}), path)) is not None:
            return error
        if (error := _canonical_uuid_error(source["stable_id"], f"{path}.stable_id")) is not None:
            return error
        if source["label"] != proposal_component_label("source", index):
            return f"{path}.label must be the exact server ordinal label"
        if (error := _validate_plugin_ref(source["plugin"], f"{path}.plugin", "source")) is not None:
            return error

    edges, error = _sequence_of_mappings(graph["edges"], "payload.graph.edges")
    if error is not None:
        return error
    assert edges is not None
    for index, edge in enumerate(edges):
        path = f"payload.graph.edges[{index}]"
        expected = frozenset({"stable_id", "from_endpoint", "to_endpoint", "flow"})
        if (error := _exact_nested_keys(edge, expected, path)) is not None:
            return error
        if (error := _canonical_uuid_error(edge["stable_id"], f"{path}.stable_id")) is not None:
            return error
        if (error := _validate_proposal_endpoint(edge["from_endpoint"], f"{path}.from_endpoint", allow_discard=False)) is not None:
            return error
        if (error := _validate_proposal_endpoint(edge["to_endpoint"], f"{path}.to_endpoint", allow_discard=True)) is not None:
            return error
        if (error := _validate_proposal_flow(edge["flow"], f"{path}.flow")) is not None:
            return error

    blockers, error = _sequence_of_mappings(payload["blockers"], "payload.blockers")
    if error is not None:
        return error
    assert blockers is not None
    if len(blockers) > _MAX_PROPOSAL_LABELS:
        return "payload.blockers exceeds the bounded size"
    blocker_targets: list[tuple[str, str]] = []
    for index, blocker in enumerate(blockers):
        path = f"payload.blockers[{index}]"
        expected = frozenset({"code", "category", "summary", "edit_target"})
        if (error := _exact_nested_keys(blocker, expected, path)) is not None:
            return error
        if blocker["code"] not in _PROPOSAL_BLOCKER_CATEGORY:
            return f"{path}.code is not allowlisted"
        if blocker["category"] != _PROPOSAL_BLOCKER_CATEGORY[blocker["code"]]:
            return f"{path}.category does not match its blocker code"
        if blocker["summary"] != _PROPOSAL_BLOCKER_SUMMARY[blocker["code"]]:
            return f"{path}.summary must be the exact blocker template id"
        if blocker["edit_target"] is not None and (error := _validate_component_target(blocker["edit_target"], f"{path}.edit_target")):
            return error
        if blocker["edit_target"] is not None:
            blocker_targets.append((blocker["edit_target"]["kind"], blocker["edit_target"]["stable_id"]))

    nodes, error = _sequence_of_mappings(payload["nodes"], "payload.nodes")
    if error is not None:
        return error
    assert nodes is not None
    for index, node in enumerate(nodes):
        path = f"payload.nodes[{index}]"
        expected = frozenset({"stable_id", "label", "node_type", "plugin", "behavior"})
        if (error := _exact_nested_keys(node, expected, path)) is not None:
            return error
        if (error := _canonical_uuid_error(node["stable_id"], f"{path}.stable_id")) is not None:
            return error
        if node["label"] != proposal_component_label("node", index):
            return f"{path}.label must be the exact server ordinal label"
        if (error := _validate_node_behavior(node["node_type"], node["behavior"], path)) is not None:
            return error
        if node["node_type"] in ("transform", "aggregation"):
            if (error := _validate_plugin_ref(node["plugin"], f"{path}.plugin", "transform")) is not None:
                return error
        elif node["plugin"] is not None:
            return f"{path}.plugin must be null for a structural node"

    outputs, error = _sequence_of_mappings(payload["outputs"], "payload.outputs")
    if error is not None:
        return error
    assert outputs is not None
    for index, output in enumerate(outputs):
        path = f"payload.outputs[{index}]"
        expected = frozenset({"stable_id", "label", "plugin"})
        if (error := _exact_nested_keys(output, expected, path)) is not None:
            return error
        if (error := _canonical_uuid_error(output["stable_id"], f"{path}.stable_id")) is not None:
            return error
        if output["label"] != proposal_component_label("output", index):
            return f"{path}.label must be the exact server ordinal label"
        if (error := _validate_plugin_ref(output["plugin"], f"{path}.plugin", "sink")) is not None:
            return error

    targets, error = _sequence_of_mappings(payload["edit_targets"], "payload.edit_targets")
    if error is not None:
        return error
    assert targets is not None
    if len(targets) > _MAX_PROPOSAL_EDGES + 3 * _MAX_PROPOSAL_COMPONENTS:
        return "payload.edit_targets exceeds the bounded size"
    edit_targets: list[tuple[str, str]] = []
    for index, target in enumerate(targets):
        if (error := _validate_component_target(target, f"payload.edit_targets[{index}]")) is not None:
            return error
        edit_targets.append((target["kind"], target["stable_id"]))

    component_ids = {
        "source": {source["stable_id"] for source in sources},
        "edge": {edge["stable_id"] for edge in edges},
        "node": {node["stable_id"] for node in nodes},
        "output": {output["stable_id"] for output in outputs},
    }
    all_ids = [
        *(source["stable_id"] for source in sources),
        *(edge["stable_id"] for edge in edges),
        *(node["stable_id"] for node in nodes),
        *(output["stable_id"] for output in outputs),
    ]
    if len(all_ids) != len(set(all_ids)):
        return "payload component stable IDs must be globally unique"

    actual_counts = {
        "sources": len(sources),
        "nodes": len(nodes),
        "edges": len(edges),
        "outputs": len(outputs),
    }
    if dict(counts) != actual_counts:
        return "payload.component_counts must match the exact structural projection"

    component_kind_by_id = {stable_id: kind for kind in ("source", "node", "output") for stable_id in component_ids[kind]}
    node_by_id = {node["stable_id"]: node for node in nodes}
    discard_id = "__proposal_discard__"
    adjacency: dict[str, set[str]] = {stable_id: set() for stable_id in component_kind_by_id}
    adjacency[discard_id] = set()
    reverse_adjacency: dict[str, set[str]] = {stable_id: set() for stable_id in adjacency}
    outgoing_flows: dict[str, list[Mapping[str, Any]]] = {}
    incoming_edges: dict[str, list[tuple[str, Mapping[str, Any]]]] = {}
    gate_routes: dict[str, list[str]] = {}
    gate_forks: dict[str, list[tuple[tuple[str, ...], str]]] = {}
    branch_origins: dict[str, list[str]] = {}
    branch_adjacency: dict[str, dict[str, set[str]]] = {}
    branch_uses: list[tuple[str, str, str, str]] = []

    for index, edge in enumerate(edges):
        path = f"payload.graph.edges[{index}]"
        from_endpoint = edge["from_endpoint"]
        to_endpoint = edge["to_endpoint"]
        flow = edge["flow"]
        assert isinstance(from_endpoint, Mapping) and isinstance(to_endpoint, Mapping) and isinstance(flow, Mapping)
        from_stable_id = from_endpoint["stable_id"]
        from_kind = from_endpoint["kind"]
        if component_kind_by_id.get(from_stable_id) != from_kind:
            return f"{path}.from_endpoint kind and stable_id do not resolve together"
        if to_endpoint["kind"] == "discard":
            to_stable_id = discard_id
            to_kind = "discard"
        else:
            to_stable_id = to_endpoint["stable_id"]
            to_kind = to_endpoint["kind"]
            if component_kind_by_id.get(to_stable_id) != to_kind:
                return f"{path}.to_endpoint kind and stable_id do not resolve together"
        flow_kind = flow["kind"]
        expected_from_kind = (
            "source"
            if flow_kind in ("source_success", "source_validation_failure")
            else "output"
            if flow_kind == "output_write_failure"
            else "node"
        )
        if from_kind != expected_from_kind:
            return f"{path}.flow is not legal for its from_endpoint kind"
        if from_kind == "node":
            node_type = node_by_id[from_stable_id]["node_type"]
            legal_node_flows = {
                "transform": frozenset({"node_success", "node_error"}),
                "aggregation": frozenset({"node_success", "node_error"}),
                "gate": frozenset({"gate_route", "gate_fork"}),
                "queue": frozenset({"queue_continue"}),
                "coalesce": frozenset({"coalesce_success"}),
            }
            if flow_kind not in legal_node_flows[node_type]:
                return f"{path}.flow is not legal for its node_type"
        legal_to_kinds = {
            "source_success": frozenset({"node", "output"}),
            "source_validation_failure": frozenset({"output", "discard"}),
            "node_success": frozenset({"node", "output"}),
            "node_error": frozenset({"node", "output", "discard"}),
            "gate_route": frozenset({"node", "output", "discard"}),
            "gate_fork": frozenset({"node", "output"}),
            "queue_continue": frozenset({"node", "output"}),
            "coalesce_success": frozenset({"node", "output"}),
            "output_write_failure": frozenset({"output", "discard"}),
        }
        if to_kind not in legal_to_kinds[flow_kind]:
            return f"{path}.flow is not legal for its to_endpoint kind"
        if from_stable_id == to_stable_id:
            return f"{path} is a self-loop"
        branch = flow.get("branch")
        if to_kind == "node" and node_by_id[to_stable_id]["node_type"] == "coalesce" and branch is None:
            return f"{path}.flow into a coalesce node requires a branch alias"
        adjacency[from_stable_id].add(to_stable_id)
        reverse_adjacency[to_stable_id].add(from_stable_id)
        outgoing_flows.setdefault(from_stable_id, []).append(flow)
        incoming_edges.setdefault(to_stable_id, []).append((from_stable_id, flow))
        if flow_kind == "gate_route":
            gate_routes.setdefault(from_stable_id, []).append(flow["route"])
        elif flow_kind == "gate_fork":
            gate_forks.setdefault(from_stable_id, []).append((tuple(flow["routes"]), flow["branch"]))
            branch_origins.setdefault(flow["branch"], []).append(to_stable_id)
        if branch is not None:
            branch_graph = branch_adjacency.setdefault(branch, {})
            branch_graph.setdefault(from_stable_id, set()).add(to_stable_id)
            branch_graph.setdefault(to_stable_id, set())
            branch_uses.append((branch, from_stable_id, flow_kind, path))

    for node in nodes:
        behavior = node["behavior"]
        assert isinstance(behavior, Mapping)
        stable_id = node["stable_id"]
        flow_kinds = tuple(flow["kind"] for flow in outgoing_flows.get(stable_id, ()))
        if node["node_type"] in ("transform", "aggregation"):
            if flow_kinds.count("node_success") != 1 or flow_kinds.count("node_error") != 1 or len(flow_kinds) != 2:
                return "payload transform and aggregation nodes require exact success and error flows"
        elif node["node_type"] == "gate":
            direct_routes = gate_routes.get(stable_id, ())
            if len(direct_routes) != len(set(direct_routes)):
                return "payload gate direct route aliases must each resolve exactly once"
            fork_routes = tuple(route for routes, _ in gate_forks.get(stable_id, ()) for route in routes)
            if set(direct_routes) & set(fork_routes):
                return "payload gate route alias cannot select both a direct target and a fork fanout"
            projected_routes = tuple(dict.fromkeys([*direct_routes, *fork_routes]))
            if projected_routes != tuple(behavior["route_aliases"]):
                return "payload gate route aliases do not match its projected flows"
            if tuple(gate_forks.get(stable_id, ())) != tuple((tuple(item["routes"]), item["branch"]) for item in behavior["fork_branches"]):
                return "payload gate fork branches do not match its projected flows"
        elif node["node_type"] == "queue":
            if flow_kinds != ("queue_continue",):
                return "payload queue node requires exactly one queue_continue flow"
            if not incoming_edges.get(stable_id):
                return "payload queue node requires at least one authoritative producer flow"
            queue_target = next(iter(adjacency[stable_id]))
            if queue_target not in node_by_id or node_by_id[queue_target]["node_type"] == "queue":
                return "payload queue continuation must target one ordinary non-queue node"
        elif node["node_type"] == "coalesce":
            if flow_kinds != ("coalesce_success",):
                return "payload coalesce node requires exactly one coalesce_success flow"
            incoming_branches = tuple(flow["branch"] for _, flow in incoming_edges.get(stable_id, ()) if flow.get("branch") is not None)
            if incoming_branches != tuple(behavior["branch_aliases"]):
                return "payload coalesce branch aliases do not match its incoming flows"

    for source in sources:
        flow_kinds = tuple(flow["kind"] for flow in outgoing_flows.get(source["stable_id"], ()))
        if flow_kinds.count("source_success") != 1 or flow_kinds.count("source_validation_failure") != 1 or len(flow_kinds) != 2:
            return "payload source requires exact success and validation-failure flows"

    output_failure_targets: dict[str, str] = {}
    for output in outputs:
        stable_id = output["stable_id"]
        output_flows = outgoing_flows.get(stable_id, ())
        if len(output_flows) != 1 or output_flows[0]["kind"] != "output_write_failure":
            return "payload output requires exactly one write-failure flow"
        failure_targets = adjacency[stable_id]
        assert len(failure_targets) == 1
        output_failure_targets[stable_id] = next(iter(failure_targets))
    for target_id in output_failure_targets.values():
        if target_id in component_ids["output"] and output_failure_targets.get(target_id) != discard_id:
            return "payload output write-failure flows cannot form a failure chain"

    all_route_aliases = [alias for node in nodes if node["node_type"] == "gate" for alias in node["behavior"]["route_aliases"]]
    if len(all_route_aliases) != len(set(all_route_aliases)):
        return "payload route aliases must be globally unique across gate nodes"
    route_aliases = set(all_route_aliases)
    expected_routes = {proposal_structural_label("route", index) for index in range(len(route_aliases))}
    if route_aliases != expected_routes:
        return "payload route aliases must form one exact global server-ordinal sequence"
    branch_aliases = set(branch_origins)
    expected_branches = {proposal_structural_label("branch", index) for index in range(len(branch_aliases))}
    if branch_aliases != expected_branches or any(len(origins) != 1 for origins in branch_origins.values()):
        return "payload fork branch aliases must be globally unique server ordinals"

    branch_coalesce_owner: dict[str, str] = {}
    for node in nodes:
        if node["node_type"] != "coalesce":
            continue
        behavior = node["behavior"]
        assert isinstance(behavior, Mapping)
        for branch in behavior["branch_aliases"]:
            existing_owner = branch_coalesce_owner.get(branch)
            if existing_owner is not None and existing_owner != node["stable_id"]:
                return "payload fork branch alias cannot be consumed by more than one coalesce node"
            branch_coalesce_owner[branch] = node["stable_id"]

    for branch, from_stable_id, flow_kind, path in branch_uses:
        origins = branch_origins.get(branch)
        if origins is None or len(origins) != 1:
            return f"{path}.flow branch alias has no unique authoritative gate_fork origin"
        if flow_kind == "gate_fork":
            continue
        branch_graph = branch_adjacency[branch]
        frontier = list(origins)
        visited = set(frontier)
        while frontier:
            current = frontier.pop()
            for target_id in branch_graph.get(current, set()) - visited:
                visited.add(target_id)
                frontier.append(target_id)
        if from_stable_id not in visited:
            return f"{path}.flow branch alias is not downstream of its authoritative gate_fork origin"

    for node in nodes:
        if node["node_type"] != "coalesce":
            continue
        behavior = node["behavior"]
        assert isinstance(behavior, Mapping)
        for branch in behavior["branch_aliases"]:
            origins = branch_origins.get(branch)
            if origins is None:
                return "payload coalesce branch alias has no authoritative gate_fork origin"
            branch_graph = branch_adjacency[branch]
            frontier = list(origins)
            visited = set(frontier)
            while frontier:
                current = frontier.pop()
                for target_id in branch_graph.get(current, set()) - visited:
                    visited.add(target_id)
                    frontier.append(target_id)
            if node["stable_id"] not in visited:
                return "payload coalesce branch is not connected to its gate_fork origin"

    indegree = dict.fromkeys(component_kind_by_id, 0)
    for from_id, target_ids in adjacency.items():
        if from_id == discard_id:
            continue
        for target_id in target_ids:
            if target_id != discard_id:
                indegree[target_id] += 1
    frontier = [stable_id for stable_id, degree in indegree.items() if degree == 0]
    visited_count = 0
    while frontier:
        current = frontier.pop()
        visited_count += 1
        for target_id in adjacency[current]:
            if target_id == discard_id:
                continue
            indegree[target_id] -= 1
            if indegree[target_id] == 0:
                frontier.append(target_id)
    if visited_count != len(component_kind_by_id):
        return "payload graph contains a cycle"

    reachable = set(component_ids["source"])
    frontier = list(reachable)
    while frontier:
        current = frontier.pop()
        for target_id in adjacency[current] - reachable:
            reachable.add(target_id)
            frontier.append(target_id)
    if (component_ids["node"] | component_ids["output"]) - reachable:
        return "payload graph contains a component unreachable from every source"

    reaches_terminal = set(component_ids["output"]) | {discard_id}
    frontier = list(reaches_terminal)
    while frontier:
        current = frontier.pop()
        for source_id in reverse_adjacency[current] - reaches_terminal:
            reaches_terminal.add(source_id)
            frontier.append(source_id)
    if (component_ids["source"] | component_ids["node"]) - reaches_terminal:
        return "payload graph contains a source or node that does not reach an output or discard"

    for owner, resolved_targets in (("payload.blockers", blocker_targets), ("payload.edit_targets", edit_targets)):
        if len(resolved_targets) != len(set(resolved_targets)):
            return f"{owner} contains a duplicate target"
        for kind, stable_id in resolved_targets:
            if stable_id not in component_ids[kind]:
                return f"{owner} target kind and stable_id do not resolve to the same component"
    return None


_PAYLOAD_VALIDATORS: Mapping[TurnType, Callable[[Mapping[str, Any]], str | None]] = {
    TurnType.INSPECT_AND_CONFIRM: _validate_inspect_payload,
    TurnType.SINGLE_SELECT: _validate_single_select_payload,
    TurnType.MULTI_SELECT_WITH_CUSTOM: _validate_multi_select_payload,
    TurnType.SCHEMA_FORM: _validate_schema_form_payload,
    TurnType.REVIEW_COMPONENTS: _validate_component_review_payload,
    TurnType.PROPOSE_PIPELINE: _validate_propose_pipeline_payload,
    TurnType.CONFIRM_WIRING: _validate_wire_payload,
}


def validate_payload(turn_type: TurnType, payload: Mapping[str, Any]) -> str | None:
    """Validate that *payload* satisfies the schema for *turn_type*.

    Validates top-level required keys, then dispatches to an exact recursive
    validator for every current turn type. Error messages are path-rooted using
    dot notation so the caller can locate the offending field:
    ``"payload.observed.columns missing"`` rather than ``"columns missing"``.

    Returns None on success, or a human-readable error string on failure.
    Raises ValueError if turn_type is not a known TurnType.
    """
    if not isinstance(turn_type, TurnType):
        raise ValueError(f"unknown turn type: {turn_type!r}")
    required = _REQUIRED_KEYS[turn_type]
    missing = required - payload.keys()
    if missing:
        return f"payload for {turn_type.value} missing required keys: {sorted(missing)}"
    unexpected = payload.keys() - _ALLOWED_KEYS[turn_type]
    if unexpected:
        return f"payload for {turn_type.value} has unexpected keys: {sorted(unexpected)}"

    return _PAYLOAD_VALIDATORS[turn_type](payload)


def validate_proposal_catalog_refs(
    payload: Mapping[str, Any],
    catalog_plugin_ids: Mapping[str, frozenset[str]],
) -> str | None:
    """Validate Task-4 proposal/catalog equivalence at the publication seam.

    The generic wire decoder can prove that plugin references are identifiers,
    not prose. Only the authoritative catalog can prove membership. The future
    durable proposal adapter must call this boundary after verifying the same
    ids against the private proposal and before persisting/emitting the turn.
    """
    if (error := validate_payload(TurnType.PROPOSE_PIPELINE, payload)) is not None:
        return error
    if set(catalog_plugin_ids) != {"source", "transform", "sink"}:
        return "proposal catalog authority must provide exact source, transform, and sink sets"
    graph = payload["graph"]
    assert isinstance(graph, Mapping)
    references: list[tuple[str, Mapping[str, Any]]] = []
    for source in cast(Sequence[Mapping[str, Any]], graph["sources"]):
        references.append(("payload.graph.sources", source["plugin"]))
    for node in cast(Sequence[Mapping[str, Any]], payload["nodes"]):
        if node["plugin"] is not None:
            references.append(("payload.nodes", node["plugin"]))
    for output in cast(Sequence[Mapping[str, Any]], payload["outputs"]):
        references.append(("payload.outputs", output["plugin"]))
    for path, reference in references:
        kind = reference["kind"]
        if reference["id"] not in catalog_plugin_ids[kind]:
            return f"{path}.plugin does not resolve in the authoritative catalog"
    return None
